### ISSUE TITLE
Text isn't highlight-able/copy-able

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/github_labels#1]
I don't like the way the text of the labels is done. You can't highlight or copy it:

![Peek 2021-12-23 10-42](https://user-images.githubusercontent.com/2385329/147167166-56cb65e7-16e3-4560-9cc4-a333a9e2252b.gif)

That last highlight and copy results in pasting this: `Remove the and labels`
Pretty sure that's not good for SEO either...

The text is done via CSS. So if that's turned off (e.g. printing or Firefox's Reading View), you get this:

![image](https://user-images.githubusercontent.com/2385329/147167381-0cdc6ec0-2c7a-4f32-930c-5fd18367b314.png)

**Comment by bugfolder** [comment]
Yeah, good point. That's a residue from the previous all-CSS solution, but now the text should be included directly. Will make a PR to update.
