### ISSUE TITLE
GitHub Labels improvement: use config instead of/in addition to cache

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/github_labels#7]
From a Zulip conversation with @docwilmot:

In the GitHub Labels module implementing the GitHub labels (currently only used here), it might be better to store all the information in config, rather than cache, or perhaps in addition to cache, as in:

Try to retrieve from cache if possible
If cache is empty, retrieve from config
Update config whenever the settings page is saved.
Possibly in the future, figure out how to update when GH changes something, but for now, rely on the fact that changes to the GH labels are very infrequent and config can be updated when needed by re-saving settings.

**Comment by klonos** [comment]
I was actually thinking updating things via cron. Once every 24hrs should be enough.

**Comment by bugfolder** [comment]
That makes sense.

Things that update regularly (like with cron) should be stored in state, not config. If we're storing this info in state, then there's no need for cache at all, right? (They're both in the db.)
